### ISSUE TITLE
Adjust password generator to satisfy password policy

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#102]
I've got this error when registering a new user:
```
"Passwords must have at least one lowercase ('a'-'z')."
```

Please either adjust the password generator to satisfy the default Asp.Net Core Identity password policy, or define the policy explicitly to match with our password generator logic.

https://github.com/Polyrific-Inc/OpenCatapult/blob/19728dd31890b59afaef4a63271b6b129b211edc/src/API/Polyrific.Catapult.Api.Infrastructure/IdentityInjection.cs#L14

**Comment by BrainBalaka** [comment]
resolved
