### ISSUE TITLE
Modify project member display

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#115]
When I run `member list -p ProjectA`, it displays the project member details as:
```
Project members:

  Id: 1
  ProjectId: 1
  UserId: 2
  ProjectMemberRoleId: 1
```

I think it doesn't help at all. Please change it so it's shown to be something like:
```
Project members:

  UserId: 1
  UserName: user@example.com
  Role: Owner
```

**Comment by BrainBalaka** [comment]
resolved
