### ISSUE TITLE
GithubRepository provider cannot load git2-8e0b172.dll

### ISSUE THREAD

**Issue by BrainBalaka** [Polyrific-Inc/OpenCatapult#118]
## Summary
I keep getting the following error when using LibGit2Sharp method such as `Clone`:
```
InnerException = {System.DllNotFoundException: Unable to load DLL 'git2-8e0b172' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at LibGit2Sharp.Core.NativeMethods.git_libgit2_init()
   at LibGit2Sharp.Core.Nati...
```

After investigation, the mentioned dll is available on the LibGit2Sharp dependency: `LibGit2Sharp.NativeBinaries`. However, this dll is not generated when we build the solution. One way to get it generated is to run `dotnet publish` on the GitHub plugin project. Even so, the MEF still could not get it since it's inside the `/runtime` folder, which contain several os folder:
![image](https://user-images.githubusercontent.com/5100736/47078641-ef99de80-d22d-11e8-999d-f8c789ada029.png)

My work around currently to make it work is to copy the `git2-8e0b172.dll` under the `runtimes\win-x64` folder to the plugin folder.

We need to find a way to automatically resolve this dll, both in dev and prod

**Comment by frandi** [comment]
This issue can be solved by using build script, which contains all steps that are required to run catapult. By having this build script, we just need to run a single command, which will replace all steps in our "Getting Started" page in docs. I've planned to create this script as part of MVP version release.

In context of this issue, we can put the steps to publish and copy the required assembly to the correct folder in the build script.

**Comment by BrainBalaka** [comment]
Understood. In that case I'll remove the label bug for this issue. I guess it's good to leave this issue open until the script is created, as a reminder

**Comment by BrainBalaka** [comment]
resolved by build script. PR #169
