### ISSUE TITLE
Provide `get` commands for all entity

### ISSUE THREAD

**Issue by BrainBalaka** [Polyrific-Inc/OpenCatapult#144]
## Summary
Currently some of the entity have `get` and `list` commands. The `list` command will only display the direct properties of the entity, while get` command will display all of the entity properties, including the child properties.

We should make this consistent throughout all entities

**Comment by frandi** [comment]
An exception for Project Member I think. In most of the time, the command `member list` is sufficient for any context that user might need.

**Comment by BrainBalaka** [comment]
I think the `Account` entity does not really need the `get` command, since it does not really have any child properties

**Comment by BrainBalaka** [comment]
done
