### ISSUE TITLE
Connection string input should not be masked

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#212]
I'm trying to create a project by using `sample` template. When it prompts me with the additional config for `EntityFrameworkCore` provider, the input text for Connection String is masked which makes me difficult to enter the value. Let's display plain text for the Connection String input.

![obfuscated](https://user-images.githubusercontent.com/1967854/49273321-2b6bc900-f4a7-11e8-86e9-74cf8839e08d.jpg)

**Comment by BrainBalaka** [comment]
done
