### ISSUE TITLE
Rename `Config` into `Properties` in Service CLI

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#248]
When I do `service get` command it shows something like:
```
External Service github-default:
  Id: 1
  Name: github-default
  Description: NULL
  ExternalServiceTypeName: GitHub
  Config:
    RemoteCredentialType: authToken
    RepoAuthToken: ****
```

Let's rename the `Config` into `Properties` because it is the term that is used in other commands (both in `service add` and `service update`).

**Comment by BrainBalaka** [comment]
done
