### ISSUE TITLE
AppServiceApp provider issue

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#252]
I got error which seems to be caused by invalid App Key: `AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.`.  It's okay, because the error message is obvious for me. 

Unfortunately the process just hung after 5 unsuccessful attempts. Can we detect the error message so we don't have to retry the process for every error? It makes sense to do it for connection error, but it isn't useful for the invalid key error and such.

**Comment by BrainBalaka** [comment]
resolved
