### ISSUE TITLE
New `queue cancel` command

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#254]
There are some cases that we need to force cancelling a job that is being run by Engine. Cancelling like this will keep the job status to `PROCESSING`. We need a way to change the status into `CANCELLED` so we can queue another jobs.

I propose to add this command to cancel a job queue:
```
queue cancel -n [queue number] -p [project name] -r [cancellation reason - optional]
```
It needs to check first if:
- the job status is `PROCESSING`
- it isn't currently being processed by any Engines

**Comment by BrainBalaka** [comment]
done
