### ISSUE TITLE
Make all components to have uniform versioning format

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#272]
At the moment we have several formats for versioning numbers, e.g:
- For core components (API, CLI, Engine libraries) we have something like `v1.0.0-alpha-[buidId]`
- For built-in plugins we have `v1.0.0.[buildId]`
- For plugin core nuget library we have `[yyyyMMdd].[counter]` version format

I would like to have a uniform versioning format starting the `beta1` release because the component will likely to be released as single package from now on.

**Comment by BrainBalaka** [comment]
done
