### ISSUE TITLE
Improvement on build-all script when starting sql server

### ISSUE THREAD

**Issue by polyrific-catapult** [Polyrific-Inc/OpenCatapult#304]
When you want to start the sql instance but you don't start powershell with elevated permission, you get this:
<img width="480" alt="build-all" src="https://user-images.githubusercontent.com/20687160/51573253-1fb2e680-1edb-11e9-8032-a2c6fb754ada.PNG">

Let's add an option to the user to continue the process or just exit, e.g:
```
You need Administrator access to start the service. Please execute the script in a shell with elevated permission or start the service manually.
Do you want to continue with the update migration process now? (y/n)
```

**Comment by BrainBalaka** [comment]
done
