### ISSUE TITLE
Multiple "invoke" messages on Engine shell for the same provider

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#308]
<img width="480" alt="engine" src="https://user-images.githubusercontent.com/1967854/51646092-c2d23180-1fa9-11e9-845c-7201e83c9343.PNG">

Why is there multiple "invoke" messages for the same provider in the shell?

Instead of for provider, what if we display the invoke message for the tasks? e.g. `Invoking "Clone" task`.

**Comment by BrainBalaka** [comment]
Because the write to console part is being called in pre, main, and post invocation. I guess we'd better move the write to console part to each task's main, instead of in the PluginManager

**Comment by BrainBalaka** [comment]
done
