### ISSUE TITLE
Offer to delete all resources when removing a project

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#310]
When removing a project, offer the user to also delete its related resources, i.e.:
- github repository (if any)
- azure app service instances (if any)

We can add a new option to the `project remove` command, e.g. `--remove-resources true`.
If the option is not included, prompt the user if she wants to remove the resources as well, e.g. `Do you want to remove the related resources as well? (y/n)`.

**Comment by BrainBalaka** [comment]
done
