### ISSUE TITLE
Create Web UI for OpenCatapult

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#320]
Create Web UI which implements OpenCatapult's basic features.

@BrainBalaka feel free to breakdown this task to suffice your need.

Task Breakdown:
* [x] Login Page
* [x] Authentication
* [x] Role Authorization
* [x] Project
  * [x] Project Member Role Authorization
  * [x] Project List
  * [x] New Project
  * [x] Project Info
* [x] Data Model
  * [x] Data Model property
* [x] Job Definition
  * [x] Job Task Definition
* [x] Job Queue
  * [x] Job Log
* [x] Manage Project member
* [x] External Service
* [x] Engine
* [x] Task Provider
* [x] User management
* [x] User profile
* [x] Forgot password

**Comment by BrainBalaka** [comment]
Task Breakdown:
* [ ] Login Page
* [ ] Authentication
* [ ] Role Authorization
* [ ] Project
  * [ ] Project Member Role Authorization
  * [ ] Project List
  * [ ] New Project
  * [ ] Project Info
* [ ] Data Model
  * [ ] Data Model property
* [ ] Job Definition
  * [ ] Job Task Definition
* [ ] Job Queue
  * [ ] Job Log
* [ ] Manage Project member
* [ ] External Service
* [ ] Engine
* [ ] Task Provider
* [ ] User management
* [ ] User profile

**Comment by frandi** [comment]
@BrainBalaka I copied your task list into the main description to improve the visibility of the progress.

**Comment by BrainBalaka** [comment]
done
