### ISSUE TITLE
Issue in Queue log command when queue number is exist in another project

### ISSUE THREAD

**Issue by BrainBalaka** [Polyrific-Inc/OpenCatapult#322]
**Describe the bug**
When we run the `queue log` command and set the queue's Number to one in another project, it will still return the queue. 

**To Reproduce**
1. Open CLI
2. add queue in projectA
3. add queue in projectB
4. execute command `queue log --project ProjectB --number {QueueIdFromProjectA}`

**Expected behavior**
The CLI should show the message "Failed getting queue {Number}. Make sure the project name and queue number are correct."

**Screenshots**
This happened when queue Id 1 is from another project, and the log file has been deleted:
![image](https://user-images.githubusercontent.com/5100736/52186964-24718600-285d-11e9-8209-0e545aadefd1.png)

**Environment (please complete the following information):**
- Component: CLI
 - OS: Any
 - Version: Beta1

**Additional context**
This issue might happened because the API is still returning the queue with the supplied Queue ID even though the Id is not in the correct project. It should return null instead

**Comment by frandi** [comment]
Done.
