### ISSUE TITLE
Implement Custom Task

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#399]
**Is your feature request related to a problem? Please describe.**
At the moment we have 8 types of the task which do specific work:
* Generate
* Build
* Clone
* Merge
* Deploy
* Deploy DB
* Publish Artifact
* Test

However in a real project, there are tasks which might not fit with one of the types, e.g. copy files, replace file content, etc.

**Describe the solution you'd like**
We need a more generic task type which can be used to create tasks that cannot be seen as one of the predefined types above.

It is actually similar to the other tasks, except that it doesn't have specifically defined task config. All configs need to be dynamically passed through `AdditionalConfigs`. It also doesn't have a specific format on the returned value, because it is dynamically composed as a dictionary object.

One characteristic of Custom Task that can be seen here is that it is more flexible than other types because there is no strict protocol in term of input arguments and returned values.

**Side notes**
At the moment (v1.0.0-beta2), all tasks do not return strongly typed value. I think it is a better idea to refactor them into strongly type values for the specific task types, and only return as Dictionary collection for Custom task.

**Comment by BrainBalaka** [comment]
Done. After consideration, the tasks does not really need to be strongly typed because we need to let the TaskProvider having a dynamic `outputValues`
