### ISSUE TITLE
Implement Generic Task Provider

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#400]
**Is your feature request related to a problem? Please describe.**
The rationale behind the idea of creating `Generic Task Provider` is that sometimes user just wants to run specific commands in a task to make use of other application tools capability. This kind of task would be overkill if requires the user to create specific Task Provider first for it.

**Describe the solution you'd like**
It would be great if we could provide a task which allows users to just provide some commands as the input, and it will be run in a terminal of their choice. Users may choose to directly enter the commands in a text box, or provide a path to a script file.

This is might relate to the proposal of [Custom Task](https://github.com/Polyrific-Inc/OpenCatapult/issues/399) implementation because it is possible that the commands being run in the `Generic Task Provider` will not fit with one of the existing task types.

The commands could be run in Windows command prompt, PowerShell, Bash, etc.

**Comment by BrainBalaka** [comment]
done
