### ISSUE TITLE
Command type issue when create external service for Github

### ISSUE THREAD

**Issue by pancawardana** [Polyrific-Inc/OpenCatapult#424]
CLI can't recognize command type when creates external service for Github

**To Reproduce**
1. Go to https://docs.opencatapult.net/guides/user-guides/sample-project#create-required-external-services
2. Type this command "dotnet occli.dll service add --name github-default --type GitHub"
3. Then you will be prompted to enter the required details for GitHub
4. Type invalid command (it can be anything)
5. Type valid command
6. CLI can't recognize the valid command 

**Expected behavior**
It should recognize the valid command 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/48673584/54897857-b06a6a80-4efc-11e9-9ec1-37f71ac15257.PNG)

**Environment (please complete the following information):**
- Component: CLI
 - OS: Windows
 - Version: Beta

**Comment by BrainBalaka** [comment]
resolved
