### ISSUE TITLE
User could not re-input the connection string on OpenCatapult API PowerShell window

### ISSUE THREAD

**Issue by zulkiflifauzi** [Polyrific-Inc/OpenCatapult#436]
Whenever i am being asked to enter the connection string on Open Catapult API PowerShell windows after running 
```powershell
.\builds\build-all.ps1
```
and i entered the wrong value, the migration process is failed and i cant re enter the new connection string.

Please ask the user for new connection string whenever the previous information is not valid.

![image](https://user-images.githubusercontent.com/735594/55208915-b02ae180-5212-11e9-9af2-bab5838469f0.png)

**Comment by BrainBalaka** [comment]
resolved
