### ISSUE TITLE
Add summarized context and instructions

### ISSUE THREAD

**Issue by BrainBalaka** [Polyrific-Inc/OpenCatapult#444]
**Is your feature request related to a problem? Please describe.**
This is similar to the "Add Help feature" issue(#443). We need to give the users a clue about what they are seeing/using. For example, we should add a one sentence (small font) explanation of what "External Service" is.

We can pick a consistent place for this, perhaps just under the heading.

Again, the point is to inform/remind the user what they are seeing. Another example would be the "Providers" tab. The user should see a brief explanation of what they are seeing:

- What are the providers for?
- Is this tab showing what the project is already using?
- How does the user get more task providers?
- How to create a custom task provider? Perhaps just link to the docs.

In line information will be very critical to adoption. Always remember that what seems obvious to us might not be obvious to our users.

**Comment by frandi** [comment]
The scope of this issue is for Web UI only so that we can add the summaries directly in the views. This scope is how it differs with https://github.com/Polyrific-Inc/OpenCatapult/issues/443 where it should reflect in both CLI and Web UI.

**Comment by BrainBalaka** [comment]
done
