### ISSUE TITLE
Add quick add menu

### ISSUE THREAD

**Issue by BrainBalaka** [Polyrific-Inc/OpenCatapult#448]
**Is your feature request related to a problem? Please describe.**
Add a quick add menu at the top right of the navigation bar, like the one in GitHub:
![image (3)](https://user-images.githubusercontent.com/5100736/55310806-9516d680-548b-11e9-9113-3212c58be825.png)

It shall have 4 menu:
- New Project
- New Engine
- New User
- New Task Provider

**Comment by zulkiflifauzi** [comment]
hi @BrainBalaka 

I will work on this ticket.

Thanks!

**Comment by BrainBalaka** [comment]
@zulkiflifauzi Please note that this issue also include the request to move Engines, Users, and Provider into a settings page:
![image (4)](https://user-images.githubusercontent.com/5100736/55326557-416bb380-54b2-11e9-9bf0-8af14945b45b.png)

**Comment by BrainBalaka** [comment]
After more discussion, we're holding off the changes to move the top menu into the profile dropdown. We're only implementing the quick add menu for now.
