### ISSUE TITLE
Problem with notificationconfig.json

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#458]
**Describe the bug**
`notificationconfig.json` file existence is currently handled when the API is starting up. However, it becomes an issue when the API is hosted in a restricted environment (like Azure App Service) where we can't create a file on runtime.

We need to change how this notification config works. If possible, let's make it like how `appsettings.json` works so we can override the values with environment variables.

**To Reproduce**
1. Deploy the API to Azure App Service.
2. Set the environment to `Development`.
3. Access the API from a browser.
4. Observe the error.

**Expected behavior**
The API should work right away after the initial deployment.

**Screenshots**
![Internal Server Error](https://user-images.githubusercontent.com/1967854/55519635-e0ef9880-56a2-11e9-9822-2e7a81fa8cfd.png)

**Environment (please complete the following information):**
- Component: API
 - Host Environment: Azure App Service
 - Version: 1.0.0-beta2 ++

**Comment by frandi** [comment]
A simple workaround, for now, is to add a predefined `notificationconfig.json` file and included in the artifact. We still need to find the permanent solution though.

**Comment by BrainBalaka** [comment]
done
