### ISSUE TITLE
Things to improve in User Registration process

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#469]
**Is your feature request related to a problem? Please describe.**
When trying to register users via Web UI, I think we can make improvements on the following things:
- Let's include `Role` in the user registration form so admin can assign the role right away when adding a user, and set `Guest` as the default selected item
- The account confirmation email needs to be modified to include the URL of the Web UI. We have done it in the `Forgot Password` feature where we differentiate the email content between the one which is requested from CLI and Web UI. However, in this `Account Confirmation` scenario we cannot use the same method because the requestor is not the user, but the Admin. I think we can add `WebUrl` in application settings which can be used by the notification service to compose the email content.
- The usage of `archive` icon for `Suspend` is not too obvious. Let's change it to `block` icon
- Please add `Email confirmed` column to the user list.

**Comment by BrainBalaka** [comment]
done
