### ISSUE TITLE
Add Version Page in Web UI

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#485]
**Is your feature request related to a problem? Please describe.**
As OpenCatapult is composed of different components, I think it is essential for the user to be able to check currently running component versions. In CLI, we have `version` command for this purpose. We need to add similar functionality in Web UI to serve the same purpose.

Let's add the following text in the page footer: `OpenCatapult Web UI v1.0.0-beta3`. It is a link which will redirect the user to a Version page that will list all component versions.

**Comment by BrainBalaka** [comment]
done
