### ISSUE TITLE
Improve API logging

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#493]
**Is your feature request related to a problem? Please describe.**
Some improvements need to be done on API logging:
- log API response (at the moment we only log the start of the requests), e.g.

![Seq(2)](https://user-images.githubusercontent.com/1967854/56456010-3f4d9400-6390-11e9-96dc-e47513fb2c62.png)

We need to also differentiate between the request and response log (maybe with the usage of prefix tag, e.g. [Req] or [Res])

- fix `IsActive` property warnings

![Seq](https://user-images.githubusercontent.com/1967854/56455961-ad458b80-638f-11e9-9d48-31bf5f2e31f8.png)

- add the requested username when login failed (currently, it only writes `Username or password is invalid`)

![Seq(1)](https://user-images.githubusercontent.com/1967854/56455981-f4cc1780-638f-11e9-9df4-86e8c4eb81ab.png)

**Comment by BrainBalaka** [comment]
done
