### ISSUE TITLE
I couldn't delete a Job definition due to reference key conflict with job queue

### ISSUE THREAD

**Issue by pancawardana** [Polyrific-Inc/OpenCatapult#499]
**Describe the bug**
I was doing the API testing using JMeter. The Job definition delete doesn't work due to reference key conflict with job queue even though the queue has been canceled

**To Reproduce**
1. Run the OpenCatapult.jmx project
2. Check `Delete Job` at `Job Queue` controller

**Expected behavior**
Job definition delete should work

**Comment by BrainBalaka** [comment]
done
