### ISSUE TITLE
Add resource name in the delete confirmation message

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#508]
**Is your feature request related to a problem? Please describe.**
When removing a resource (e.g. a project), a popup dialog appear to allow user to confirm the deletion by entering the resource name. The purpose of this process is to prevent user to delete the wrong resource. The resource name is not a secret value anyway, so it would be fine to help user finding the name easier.

![web-delete-confirm](https://user-images.githubusercontent.com/1967854/56797863-deb2d100-683f-11e9-8987-8cff3283f1cc.png)

In the project deletion sample above, we can change the message to be `Please enter project name (FrandiDemo2) to confirm project deletion:`. Please also do the same changes to other resource deletion.

**Comment by BrainBalaka** [comment]
done
