### ISSUE TITLE
Improve project creation flow

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#515]
**Is your feature request related to a problem? Please describe.**
We need to improve the project creation flow so that users won't feel complicated in the process, especially when using a project template. Well, it will be contrary to the original purpose really if users feel that using a project template will just make their life harder.

**Describe the solution you'd like**
In Web UI:
- allow users to save the project although the configs are not complete.
- put the loaded job definitions in tabs instead of as a long list to the bottom
- prevent any job to be queued until all required configs are filled

In CLI:
- add a message prior to prompting users with job definition configs: `Do you want to complete the job definition configuration now? (y/n)`. If the users choose to fill them later, please show a message after saving the project: `The project has been successfully created. However, you cannot queue the Default job until you complete the configuration.`
- prevent any job to be queued until all required configs are filled

**Comment by BrainBalaka** [comment]
done
