### ISSUE TITLE
Remove scrollbar on confirm delete popup

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#524]
**Describe the bug**
There is a scrollbar in the delete confirmation popup. Please remove it,

**To Reproduce**
1. Go to a project (or any other entities)
2. Click on `Delete` button
3. Observe the confirmation popup

**Screenshots**
![OpenCatapult Web](https://user-images.githubusercontent.com/1967854/57271238-e896c880-70b8-11e9-9d03-3207037efa19.png)

**Comment by BrainBalaka** [comment]
done
