### ISSUE TITLE
Add a flag for default job definition

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#525]
**Is your feature request related to a problem? Please describe.**
At the moment, we need to open the `Job Definition` tab to queue a job. It would be great if users could queue a default job from anywhere as long as they are in a project area scope.

**Describe the solution you'd like**
- add a `Queue Job` button next to the project's `Delete` button
- add a flag to mark a job definition as default (it would be similar to the existing `IsDeletion` flag)
- this default job definition will be run automatically when the `Queue Job` button is clicked

**Additional context**
Please also adjust the `sample-devops` template after this change.

**Comment by BrainBalaka** [comment]
done
