### ISSUE TITLE
Improve visibility of required configs in Job Definition

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#527]
**Describe the bug**
Well, this is not really a bug actually. But it will potentially bug the users if we don't resolve the issue.  At the moment, we've made a project with `sample-devops` project can be saved although the configs are not complete. And it also nicely prevents the incomplete Job Definition to be queued. However, we need to improve the visibility of the required configs so users won't be confused if they can't queue a job.

**To Reproduce**
1. Create a new project with `sample-devops` template
2. Without completing all configs, save the project
3. Try queuing the Default job
4. Observe the things that need to be improved

**Expected behavior**
- Instead of showing the message in the fading notification, can we make it in a modal window with the OK button?
- If possible, please list all the incomplete configs. If it isn't possible, just show a generic message asking the user to check the job task configs
- Can we mark the required configs with a red asterisk?

**Comment by BrainBalaka** [comment]
@frandi Related to putting the red asterisk to required configs, do mean when we create a project, or in task dialog?
The task dialog already have the asterisk to markit as required:
![image](https://user-images.githubusercontent.com/5100736/57502395-cbab0100-7315-11e9-84e8-d6d3363b9420.png)

If you meant to have it in create project form as well, I think it won't really be consistent with the UI convention that says field that have asterisk will trigger `required` validation (the asterisk is automatically added when we add `required` attribute to the `input` tag). Additionally, the form already separate the required and optional fields, with optional fields being hidden in collapsible, so I think it should be implied that the fields shown is needed. 

Maybe we can just add some wording above the job form tabs? The wording would be something like:
"Please fill out the task configurations below. You can skip this now, and fill it out later. However, you will not be able to queue the job until all required configs are set"

**Comment by frandi** [comment]
@BrainBalaka the point of the red asterisk request is to help users to navigate to the required configs easily.
There are many options that we can do, e.g:
1) highlight the incomplete tasks
![OpenCatapult Web(3)](https://user-images.githubusercontent.com/1967854/57594355-ce9e2f80-7569-11e9-9d96-e47e8183ee64.png)

2) highlight the incomplete task configs
![OpenCatapult Web(2)](https://user-images.githubusercontent.com/1967854/57594378-fdb4a100-7569-11e9-813a-ed2d618ae58e.png)

If we've applied them, we can simplify the error message into:
`The "Default" job has incomplete task configs. Please complete them before putting this job in queue.`

If this error message occur because the global `Queue` button is clicked, it would be nice if it can redirect the user to the `Job Definitions` tab, with the job tasks expanded.

Please let me know if it's too complicated to implement.

**Comment by BrainBalaka** [comment]
done
