### ISSUE TITLE
Clean any mention of `plugin` in the code into `task provider`

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#562]
This task is the last attempt to rename `plugin` into `task provider`.

Let's:
- rename `plugin.yml` into `taskprovider.yml`
- rename the default `plugins` folder in Engine structure into `taskproviders`
- rename any `Plugin*.cs` class in Engine project into `TaskProvider*.cs`
- update the docs

Note: please tackle each of the refactoring items in different PRs to smooth the process.

**Comment by BrainBalaka** [comment]
done
