### ISSUE TITLE
Implement dynamic configurations 

### ISSUE THREAD

**Issue by BrainBalaka** [Polyrific-Inc/OpenCatapult#567]
**Is your feature request related to a problem? Please describe.**
We need to provide a dynamic configuration that can be maintained by admin user. This configurations can be used for feature toggle in the opencatapult, for example admin can turn on/off the two factor authentication feature.

**Describe the solution you'd like**
Since it can be maintained by admin, the configuration shall need to be stored in database. We can then use a custom configuration provider that uses database as the source (e.g. https://medium.com/@dneimke/custom-configuration-in-net-core-2-193ff6f02046)

After the configuration is implemented, we'd also need to implement a feature toggle wrapper, which is a static class that have boolean method/properties to get the status of a feature toggle easily. This wrapper will read from the configuration implemented earlier

**Comment by frandi** [comment]
Is this complete @BrainBalaka ?

**Comment by BrainBalaka** [comment]
Yes, I'm closing this now
