### ISSUE TITLE
Simplify Project Template Preview

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#592]
**Is your feature request related to a problem? Please describe.**
We need to simplify the preview of the selected Project Template when creating a new project. This is to make the Project creation process to be as simple as possible. We can let the completion of the required fields in Job Definition to be done later.

**Describe the solution you'd like**
- Display only the task flow in the Job Definition
- Hide Deletion Job
- Display Data Models

No input needed on the preview section.

**Comment by frandi** [comment]
It's done, right @BrainBalaka ?

**Comment by BrainBalaka** [comment]
yes. I'm closing this.
