### ISSUE TITLE
Forced Log out

### ISSUE THREAD

**Issue by zulkiflifauzi** [Polyrific-Inc/OpenCatapult#593]
I experienced forced logout when trying to add a Task to a Job definition

1. Login to polyrific.opencatapult.com using my username: zulkifli.fauzi@polyrific.com
2. Choose School Management project
3. Go to Job Definitions tab
4. Click Add Task button under GenerateCode job definition.

I created a video to reproduce this issue:
https://www.screencast.com/t/ptWsVMvHFZ

Thanks!

**Comment by ahmadilham** [comment]
It also occured when trying to view a Task detail https://drive.google.com/open?id=1E36VxX9aQZjL7RCR6aSw7aAwUKfgJvQf

**Comment by frandi** [comment]
@BrainBalaka they both are `basic` users. I haven't checked the code, but if I'm not mistaken the Web UI directly routes the request to the login page when it receives `401` response. I think the fix would be:
- redirect `401` to a `No Permission` page
- trace the requests on the Job Definition area to see where the Basic users don't have permission

**Comment by frandi** [comment]
@BrainBalaka can we close this one?

**Comment by BrainBalaka** [comment]
Yes, I'm closing this
