### ISSUE TITLE
Request reset password API should not return the token

### ISSUE THREAD

**Issue by BrainBalaka** [Polyrific-Inc/OpenCatapult#70]
## Summary
Currently the GET `/Account/{userId}/resetpassword` is returning the reset password token in the API response. This would make any user can perform reset password for other user. 

Instead, we should send the token via email.

**Comment by frandi** [comment]
After the reset token is sent via email, how will it be used to reset the password? Maybe we need to change the implementation of `updatepassword` command as well?

**Comment by BrainBalaka** [comment]
I think `updatepassword` is used if we know our current password. 
While `resetpassword` will be used when we forgot our password. We'd need two new commands for this:
- `requestresetpassword` (or `forgotpassword` ?). To request a reset password token be sent into the email
- `resetpassword`. Here we input the reset password token we received in the email, and the new password.

What do you think?

**Comment by frandi** [comment]
Or.. would it be better if we make a new sub-command for `password` and gather all related actions as its sub-commands?

I imagine we will have these commands later:
- `account password update`
- `account password token`
- `account password reset`

What do you think?

**Comment by frandi** [comment]
sure, go ahead.

**Comment by BrainBalaka** [comment]
resolved
