### ISSUE TITLE
Adjust user registration process

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#84]
User registration should be done by admin's invitation only.

The flow will be:
1. Admin register new user via CLI
2. An email notification is sent to the user containing confirmation url and temporary password
3. User confirm the registration by clicking the link
4. User can login via CLI

Please also adjust the email notification content to contain:
- confirmation url
- steps to setup CLI (just a link to the docs I think)
- a recommendation to change the temporary password (link to the docs)

**Comment by BrainBalaka** [comment]
resolved
