### ISSUE TITLE
Standardize user/email options in CLI

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#89]
I found that it's a bit hard to memorize whether to use `--user` or `--email` option in CLI.

Let's make it standard to only use `--user` in all places. The value will always be an email address anyway.

**Note**: if you find any exceptions when refactoring the options, e.g. `--email` is more make sense to be used in certain context, let's discuss it first here.

Don't forget to adjust the docs and quip as well after this change.

**Comment by BrainBalaka** [comment]
@frandi what if we keep `account register` command to use `--email`, since at that point, the email is not yet a user?

**Comment by frandi** [comment]
@BrainBalaka yep agreed. It makes sense to use Email, along with FirstName and LastName.

**Comment by BrainBalaka** [comment]
resolved
