### ISSUE TITLE
Add intro message when executing commands

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#91]
We need to add intro message when executing commands so user knows what process is currently running in the background.

For example, when checking for current user, it just shows a blank space before displaying the result. We need to add an intro message so that it will display a message like `Checking for current logged-in user...` right after the user enter the command, and before the real result is displayed.

**Comment by frandi** [comment]
Done for these commands:
- login, logout, currentuser
- account related

**Comment by BrainBalaka** [comment]
@frandi Can we close this one? I've implemented it in the remaining commands

**Comment by frandi** [comment]
Yes sure, I'm closing this.
