### ISSUE TITLE
Rethinking "update password" and "reset password"

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#94]
I have given some thoughts on the different between "update password" and "reset password".

"Update password" 
- should be used by current logged-in user to update her own password
- the command shouldn't ask for the user's email again because CLI should've been able to recognized current user already. This is to prevent a user to update other user's password

"Reset password" 
- should be used by user who cannot login to her account
- she needs to request a reset password token first
- for security reason, don't show "User was not found" if the user doesn't exist. Just log it as warning saying that "A reset password token was requested for a user that doesn't exist"

**Comment by BrainBalaka** [comment]
resolved
